package spdx3

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/santhosh-tekuri/jsonschema/v6"
	"github.com/santhosh-tekuri/jsonschema/v6/kind"
	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

// The official SPDX 3.0.1 JSON Schema, embedded so that validation needs no
// network at runtime (sections 30.8 and 32.5). The file is
// https://spdx.org/schema/3.0.1/spdx-json-schema.json byte for byte, as
// published with the 3.0.1 release (generated by shacl2code from the 3.0.1
// model); TestTheEmbeddedSchemaIsTheUpstreamFile pins its SHA-256, so a
// reviewer can compare it with the published file and see that it is the same.
// It is draft 2020-12, which the vendored validator implements.
//
//go:embed schema/spdx-json-schema-3.0.1.json
var schemaJSON []byte

// schemaURL is the identifier the schema is registered under.
const schemaURL = "https://spdx.org/schema/3.0.1/spdx-json-schema.json"

// SchemaJSON returns the embedded schema, so that a user can see exactly what
// their document is checked against.
func SchemaJSON() []byte { return append([]byte(nil), schemaJSON...) }

var (
	compileOnce sync.Once
	compiledSet *schemaSet
	compileErr  error
)

var errorPrinter = message.NewPrinter(language.English)

// iriPattern is the one pattern of the schema Go's regexp cannot compile:
// $defs.IRI holds an identifier to "^(?!_:).+:.+", a negative lookahead that
// excludes blank nodes. RE2 has no lookahead, so the pattern is matched by
// hand: not a blank node, and something on both sides of a colon. Every other
// pattern of the schema is RE2 syntax and is compiled as it is.
const iriPattern = "^(?!_:).+:.+"

type iriMatcher struct{ rest *regexp.Regexp }

func (m iriMatcher) MatchString(s string) bool {
	return !strings.HasPrefix(s, "_:") && m.rest.MatchString(s)
}

func (m iriMatcher) String() string { return iriPattern }

func schemaRegexp(pattern string) (jsonschema.Regexp, error) {
	if pattern == iriPattern {
		return iriMatcher{rest: regexp.MustCompile("^.+:.+")}, nil
	}
	return regexp.Compile(pattern)
}

// nodesURL is the identifier of the small schema, built here and never
// published, that holds one @graph node of a known class to that class.
const nodesURL = "urn:sbomb:spdx-3.0.1-nodes"

// schemaSet is the compiled schema in the two forms validation uses: the
// whole document, and one @graph node per class.
//
// The published schema checks each node of @graph against AnyClass -- an
// anyOf of all 78 classes, every one of which is "if the type is mine, check
// me, else fail". A node can only ever pass the branch of its own type, but
// the validator has to evaluate all 78 to collect the annotations
// unevaluatedProperties needs, and builds an error for each of the 77 that
// fail. On a document of fifty thousand files that is most of a minute. Checking
// a node against the definition of its own type, with the same
// unevaluatedProperties the items schema puts around AnyClass, accepts and
// refuses exactly the same nodes -- the 77 other branches can only fail -- in
// a fraction of the time, and the nodes are independent of each other, so
// they are checked in parallel. A node whose type is no class is checked
// against AnyClass itself, so that it is refused in the schema's own words.
type schemaSet struct {
	document *jsonschema.Schema
	anyNode  *jsonschema.Schema
	byClass  map[string]*jsonschema.Schema
}

// compiled returns the schema, compiled once per process. The CycloneDX
// schemas have their own compiler; nothing is shared but the library.
func compiled() (*schemaSet, error) {
	compileOnce.Do(func() {
		compiledSet, compileErr = compile()
	})
	return compiledSet, compileErr
}

func compile() (*schemaSet, error) {
	document, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaJSON))
	if err != nil {
		return nil, fmt.Errorf("parsing the embedded SPDX schema: %w", err)
	}
	compiler := jsonschema.NewCompiler()
	compiler.UseRegexpEngine(schemaRegexp)
	if err := compiler.AddResource(schemaURL, document); err != nil {
		return nil, fmt.Errorf("registering the embedded SPDX schema: %w", err)
	}
	node := func(target string) map[string]any {
		return map[string]any{"type": "object", "$ref": schemaURL + "#/$defs/" + target, "unevaluatedProperties": false}
	}
	definitions := map[string]any{"AnyClass": node("AnyClass")}
	concrete := sortedKeys(classes().concrete)
	for _, class := range concrete {
		definitions[class] = node(class)
	}
	wrapper := map[string]any{"$schema": "https://json-schema.org/draft/2020-12/schema", "$defs": definitions}
	if err := compiler.AddResource(nodesURL, wrapper); err != nil {
		return nil, fmt.Errorf("registering the node schemas: %w", err)
	}
	set := &schemaSet{byClass: map[string]*jsonschema.Schema{}}
	if set.document, err = compiler.Compile(schemaURL); err != nil {
		return nil, err
	}
	if set.anyNode, err = compiler.Compile(nodesURL + "#/$defs/AnyClass"); err != nil {
		return nil, err
	}
	for _, class := range concrete {
		if set.byClass[class], err = compiler.Compile(nodesURL + "#/$defs/" + class); err != nil {
			return nil, err
		}
	}
	return set, nil
}

// ValidateAgainstSchema checks a document against the official 3.0.1 JSON
// Schema. The schema constrains shape and vocabulary -- every key, every enum,
// every cardinality -- and nothing about what refers to what; Validate adds
// that.
func ValidateAgainstSchema(data []byte) error {
	set, err := compiled()
	if err != nil {
		return err
	}
	instance, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("the document is not valid JSON: %w", err)
	}
	issues := map[string]bool{}
	root, isObject := instance.(map[string]any)
	graph, hasGraph := root["@graph"].([]any)
	if !isObject || !hasGraph {
		if err := set.document.Validate(instance); err != nil {
			collectSchemaIssues(err, nil, issues)
		}
		return schemaIssuesError(issues)
	}
	// The envelope -- @context, nothing beside @graph, @graph an array -- is
	// checked by the published schema itself, with the nodes taken out; the
	// nodes are checked one by one below.
	envelope := make(map[string]any, len(root))
	for key, value := range root {
		envelope[key] = value
	}
	envelope["@graph"] = []any{}
	if err := set.document.Validate(envelope); err != nil {
		collectSchemaIssues(err, nil, issues)
	}
	for _, found := range set.validateNodes(graph) {
		for issue := range found {
			issues[issue] = true
		}
	}
	return schemaIssuesError(issues)
}

// validateNodes checks every node of @graph, on every CPU.
func (set *schemaSet) validateNodes(graph []any) []map[string]bool {
	results := make([]map[string]bool, len(graph))
	workers := runtime.GOMAXPROCS(0)
	if workers > len(graph) {
		workers = len(graph)
	}
	next := make(chan int)
	var wait sync.WaitGroup
	for worker := 0; worker < workers; worker++ {
		wait.Add(1)
		go func() {
			defer wait.Done()
			for index := range next {
				schema := set.anyNode
				if object, ok := graph[index].(map[string]any); ok {
					if class, ok := object["type"].(string); ok && set.byClass[class] != nil {
						schema = set.byClass[class]
					}
				}
				if err := schema.Validate(graph[index]); err != nil {
					found := map[string]bool{}
					collectSchemaIssues(err, []string{"@graph", strconv.Itoa(index)}, found)
					results[index] = found
				}
			}
		}()
	}
	for index := range graph {
		next <- index
	}
	close(next)
	wait.Wait()
	return results
}

func schemaIssuesError(issues map[string]bool) error {
	if len(issues) == 0 {
		return nil
	}
	lines := make([]string, 0, len(issues))
	for issue := range issues {
		lines = append(lines, "  "+issue)
	}
	return fmt.Errorf("SPDX 3.0.1 schema validation failed:\n%s", capped(lines))
}

// collectSchemaIssues reduces a validation failure to its deepest failures,
// as locations below prefix. The raw error is a deeply nested tree that is
// unreadable in a CI log.
//
// A "false schema" leaf is how unevaluatedProperties: false reports a key no
// passing branch evaluated. When a node has a real defect -- a value of the
// wrong type, say -- the branch that would have evaluated its other keys
// fails with it, and every correct key of the node is then reported as a
// false schema too: about eight lines that blame name, spdxId and
// creationInfo for one wrong field, and under the cap of 20 they push the
// real causes of later nodes out of the report. So the false-schema leaves of
// one failure are kept only when it has no other cause. A key the class does
// not define at all is still reported, alone or on the run after the other
// defects of its node are fixed.
func collectSchemaIssues(err error, prefix []string, into map[string]bool) {
	substantive := map[string]bool{}
	unevaluated := map[string]bool{}
	gatherSchemaIssues(err, prefix, substantive, unevaluated)
	if len(substantive) == 0 {
		substantive = unevaluated
	}
	for issue := range substantive {
		into[issue] = true
	}
}

func gatherSchemaIssues(err error, prefix []string, substantive, unevaluated map[string]bool) {
	validationError, ok := err.(*jsonschema.ValidationError)
	if !ok {
		substantive[err.Error()] = true
		return
	}
	if len(validationError.Causes) == 0 {
		message := validationError.ErrorKind.LocalizedString(errorPrinter)
		// "Not a software_File" and its siblings are the else branches of
		// the classes a node is not; they say nothing about what is wrong.
		if strings.HasPrefix(message, "value must be 'Not a ") || strings.HasPrefix(message, "value must be \"Not a ") {
			return
		}
		location := "/" + strings.Join(append(append([]string(nil), prefix...), validationError.InstanceLocation...), "/")
		if _, isFalse := validationError.ErrorKind.(*kind.FalseSchema); isFalse {
			unevaluated[location+": "+message] = true
		} else {
			substantive[location+": "+message] = true
		}
		return
	}
	for _, cause := range validationError.Causes {
		gatherSchemaIssues(cause, prefix, substantive, unevaluated)
	}
}

// maxReportedIssues is how many problems a failed check lists, as the
// CycloneDX validator does: enough to fix a document by, few enough to read.
const maxReportedIssues = 20

func capped(lines []string) string {
	sort.Strings(lines)
	if len(lines) > maxReportedIssues {
		remaining := len(lines) - maxReportedIssues
		lines = append(lines[:maxReportedIssues:maxReportedIssues], fmt.Sprintf("  ... and %d more", remaining))
	}
	return strings.Join(lines, "\n")
}

// classes is the class hierarchy of the 3.0.1 model as the schema states it:
// each class's parent, read from the "allOf" of its _props definition, and
// whether it is concrete (has a definition of its own a node can be). Reading
// it from the embedded schema rather than writing it down here means the
// checks cannot disagree with the schema about what an Agent or an Element is.
type classTable struct {
	parent   map[string]string
	concrete map[string]bool
}

var (
	classesOnce sync.Once
	classInfo   classTable
)

func classes() classTable {
	classesOnce.Do(func() {
		var schema struct {
			Defs map[string]struct {
				AllOf []struct {
					Ref string `json:"$ref"`
				} `json:"allOf"`
				If json.RawMessage `json:"if"`
			} `json:"$defs"`
		}
		classInfo = classTable{parent: map[string]string{}, concrete: map[string]bool{}}
		if err := json.Unmarshal(schemaJSON, &schema); err != nil {
			return
		}
		for name, definition := range schema.Defs {
			if class, isProps := strings.CutSuffix(name, "_props"); isProps {
				for _, entry := range definition.AllOf {
					parent := strings.TrimSuffix(strings.TrimPrefix(entry.Ref, "#/$defs/"), "_props")
					if entry.Ref != "" && parent != "SHACLClass" {
						classInfo.parent[class] = parent
					}
				}
				continue
			}
			if len(definition.If) > 0 {
				classInfo.concrete[name] = true
			}
		}
	})
	return classInfo
}

// isA reports whether class is ancestor or one of its subclasses.
func isA(class, ancestor string) bool {
	table := classes()
	for depth := 0; class != "" && depth < 16; depth++ {
		if class == ancestor {
			return true
		}
		class = table.parent[class]
	}
	return false
}

// isElementClass reports whether a node of this type is an Element, which
// must stand at the top of the graph with an IRI of its own.
func isElementClass(class string) bool { return isA(class, "Element") }
