/* SPDX-License-Identifier: GPL-2.0-only
 * Copyright (C) 2026 Fixture GPL Generator Authors
 *
 * A build-time code generator. It is compiled and executed during the build
 * and no part of it is linked into the deliverable, which is the whole point:
 * a GPL tool that produced a file is not a GPL component of the product.
 */
#include <stdio.h>

int main(int argc, char **argv)
{
    FILE *out;
    int i;

    if (argc < 2) {
        return 1;
    }
    out = fopen(argv[1], "w");
    if (out == NULL) {
        return 1;
    }
    fputs("/* Generated by dep/gpl-gen/table_gen.c. Do not edit. */\n", out);
    fputs("const int foss_table[8] = {", out);
    for (i = 0; i < 8; i++) {
        fprintf(out, "%s%d", i == 0 ? "" : ", ", i * i);
    }
    fputs("};\n", out);
    fclose(out);
    return 0;
}
