// Package make reads the files generated by CMake's Makefiles generators.
package make

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/example/sbomb/internal/adapters/depfiles"
	"github.com/example/sbomb/internal/pathmodel"
	"github.com/example/sbomb/internal/respfile"
)

const maxResponseDepth = 8

var ErrInputLimitExceeded = errors.New("make adapter input limit exceeded")

// Target contains the evidence CMake emits for one target directory.
type Target struct {
	Name            string
	Directory       string
	ObjectSources   map[string]string
	LinkInputs      []string
	ObjectDeps      map[string][]string
	CompilerDepend  string
	DependencyFiles []string
}

// Build is the normalized Makefiles evidence for a build directory.
type Build struct {
	BuildDir string
	Targets  []Target
}

// Parse discovers CMake target directories below buildDir and reads their
// build.make, link.txt, DependInfo.cmake, and dependency files.
// Parse reads a build tree produced by one of CMake's Makefiles generators.
//
// It requires a Makefile at the build root. Every CMake build has a
// CMakeFiles directory whatever generator wrote it, so keying on that alone
// made this adapter walk a Ninja build tree and read every dependency file in
// it -- work whose evidence the Ninja adapter already supplies from
// .ninja_deps, and which dominated the run at scale.
func Parse(buildDir string) (*Build, error) {
	if _, err := os.Stat(filepath.Join(buildDir, "Makefile")); err != nil {
		return nil, fmt.Errorf("not a Makefiles build tree: %w", err)
	}
	entries, err := os.ReadDir(filepath.Join(buildDir, "CMakeFiles"))
	if err != nil {
		return nil, err
	}
	result := &Build{BuildDir: buildDir}
	for _, entry := range entries {
		if !entry.IsDir() || !strings.HasSuffix(entry.Name(), ".dir") {
			continue
		}
		target, err := parseTarget(buildDir, entry.Name())
		if err != nil {
			return nil, err
		}
		if len(target.ObjectSources) == 0 && len(target.LinkInputs) == 0 && len(target.ObjectDeps) == 0 {
			continue
		}
		result.Targets = append(result.Targets, target)
	}
	return result, nil
}

func parseTarget(buildDir, directoryName string) (Target, error) {
	directory := filepath.Join(buildDir, "CMakeFiles", directoryName)
	target := Target{
		Name:          strings.TrimSuffix(directoryName, ".dir"),
		Directory:     directory,
		ObjectSources: make(map[string]string),
		ObjectDeps:    make(map[string][]string),
	}
	if err := parseBuildMake(filepath.Join(directory, "build.make"), buildDir, &target); err != nil && !os.IsNotExist(err) {
		return Target{}, err
	}
	if inputs, err := parseLinkFile(filepath.Join(directory, "link.txt"), buildDir); err == nil {
		target.LinkInputs = inputs
	} else if !os.IsNotExist(err) {
		return Target{}, err
	}
	if err := parseDependInfo(filepath.Join(directory, "DependInfo.cmake"), buildDir, &target); err != nil && !os.IsNotExist(err) {
		return Target{}, err
	}
	if err := parseDependencyFiles(directory, &target); err != nil {
		return Target{}, err
	}
	return target, nil
}

func parseBuildMake(path, buildDir string, target *Target) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	for _, logical := range logicalLines(string(data)) {
		line := strings.TrimSpace(logical)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "\t") {
			continue
		}
		colon := strings.IndexByte(line, ':')
		if colon <= 0 {
			continue
		}
		object := strings.TrimSpace(line[:colon])
		if !looksLikeObject(object) {
			continue
		}
		objectPath := resolvePath(buildDir, object)
		if _, resolved := target.ObjectSources[objectPath]; resolved {
			continue
		}
		for _, prerequisite := range splitShellWords(line[colon+1:]) {
			if looksLikeSource(prerequisite) {
				target.ObjectSources[objectPath] = resolvePath(buildDir, prerequisite)
				break
			}
		}
	}
	return nil
}

func parseLinkFile(path, buildDir string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	// Section 9.3: the link line of a large target lives in a response file,
	// and CMake writes one for every Windows link. The shared expander applies
	// the depth and size limits and the quoting rules of the detected
	// toolchain.
	words := splitShellWords(string(data))
	var linker string
	if len(words) > 0 {
		linker = words[0]
	}
	args, err := respfile.Expand(words, respfile.Options{
		Dir:      filepath.Dir(path),
		Quoting:  respfile.QuotingForCompiler(linker),
		MaxDepth: maxResponseDepth,
	})
	if err != nil {
		return nil, err
	}
	inputs := make([]string, 0)
	for _, arg := range args {
		if arg == "-o" || strings.HasPrefix(arg, "-") || arg == "@" {
			continue
		}
		if strings.HasSuffix(arg, ".o") || strings.HasSuffix(arg, ".obj") || strings.HasSuffix(arg, ".a") || strings.HasSuffix(arg, ".so") || strings.HasSuffix(arg, ".lib") {
			inputs = append(inputs, resolvePath(buildDir, arg))
		}
	}
	return unique(inputs), nil
}

func parseDependInfo(path, buildDir string, target *Target) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	quoted := quotedStrings(string(data))
	for index := 0; index+1 < len(quoted); index += 4 {
		source, object := quoted[index], quoted[index+1]
		if strings.Contains(object, ".o") || strings.Contains(object, ".obj") {
			target.ObjectSources[resolvePath(buildDir, object)] = resolvePath(buildDir, source)
		}
	}
	return nil
}

func parseDependencyFiles(directory string, target *Target) error {
	buildRoot := filepath.Dir(filepath.Dir(directory))
	for _, name := range []string{"compiler_depend.make", "depend.make"} {
		path := filepath.Join(directory, name)
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return err
		}
		rules, err := depfiles.Parse(string(data))
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		target.CompilerDepend = path
		for _, rule := range rules {
			for _, object := range rule.Targets {
				target.ObjectDeps[resolvePath(buildRoot, object)] = resolvePaths(buildRoot, rule.Prereqs)
			}
		}
	}
	if len(target.ObjectDeps) != 0 {
		return nil
	}
	return filepath.WalkDir(directory, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".d") {
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		rules, parseErr := depfiles.Parse(string(data))
		if parseErr != nil {
			return fmt.Errorf("parse %s: %w", path, parseErr)
		}
		target.DependencyFiles = append(target.DependencyFiles, path)
		for _, rule := range rules {
			for _, object := range rule.Targets {
				target.ObjectDeps[resolvePath(buildRoot, object)] = resolvePaths(buildRoot, rule.Prereqs)
			}
		}
		return nil
	})
}

func logicalLines(text string) []string {
	text = strings.ReplaceAll(text, "\\\r\n", "")
	text = strings.ReplaceAll(text, "\\\n", "")
	return strings.Split(text, "\n")
}

func splitShellWords(text string) []string {
	var result []string
	var word strings.Builder
	var quote rune
	escaped := false
	flush := func() {
		if word.Len() > 0 {
			result = append(result, word.String())
			word.Reset()
		}
	}
	for _, char := range text {
		if escaped {
			word.WriteRune(char)
			escaped = false
			continue
		}
		if char == '\\' && quote != '\'' {
			escaped = true
			continue
		}
		if quote != 0 {
			if char == quote {
				quote = 0
			} else {
				word.WriteRune(char)
			}
			continue
		}
		if char == '\'' || char == '"' {
			quote = char
		} else if unicode.IsSpace(char) {
			flush()
		} else {
			word.WriteRune(char)
		}
	}
	flush()
	return result
}

func quotedStrings(text string) []string {
	var result []string
	for len(text) > 0 {
		start := strings.IndexByte(text, '"')
		if start < 0 {
			break
		}
		text = text[start+1:]
		end := strings.IndexByte(text, '"')
		if end < 0 {
			break
		}
		result = append(result, strings.ReplaceAll(text[:end], "\\\"", "\""))
		text = text[end+1:]
	}
	return result
}

func looksLikeObject(path string) bool {
	return strings.HasSuffix(path, ".o") || strings.HasSuffix(path, ".obj")
}

// sourceExtensions is the set of compiler inputs that can produce a linked
// object, per specification section 14.6. It is deliberately an allowlist: a
// generated build.make lists bookkeeping prerequisites such as flags.make and
// compiler_depend.ts alongside the real source, and a blocklist would accept
// those as the translation unit.
var sourceExtensions = map[string]bool{
	".c": true, ".cc": true, ".cpp": true, ".cxx": true, ".c++": true,
	".m": true, ".mm": true,
	".s": true, ".asm": true,
	".cu": true,
	".rc": true, ".def": true,
}

func looksLikeSource(path string) bool {
	if strings.HasPrefix(path, "$(") {
		return false
	}
	// .S and .s are both assembly; extensions are otherwise case-insensitive
	// only on Windows, but CMake emits them as written, so compare lowercased.
	return sourceExtensions[strings.ToLower(filepath.Ext(path))]
}
func resolvePath(base, path string) string {
	if pathmodel.IsAbsolute(path) {
		return filepath.Clean(path)
	}
	return filepath.Clean(filepath.Join(base, path))
}
func resolvePaths(base string, paths []string) []string {
	result := make([]string, 0, len(paths))
	for _, path := range paths {
		result = append(result, resolvePath(base, path))
	}
	return result
}
func unique(items []string) []string {
	seen := map[string]bool{}
	result := make([]string, 0, len(items))
	for _, item := range items {
		if !seen[item] {
			seen[item] = true
			result = append(result, item)
		}
	}
	return result
}
