package generate

import (
	"os"
	"path/filepath"
	"testing"
)

// The unity and precompiled-header parsers read generated files from somebody
// else's build tree. Section 30 makes that untrusted input.
func FuzzUnityIncludes(f *testing.F) {
	f.Add("/* generated by CMake */\n#include \"/src/main.c\"\n")
	f.Add("#include <a.c>\n#include \"b.c\"\n")
	f.Add("/* unterminated\n#include \"a.c\"\n")
	f.Add("#include \"\n")
	f.Add("#includ")
	f.Add("")

	f.Fuzz(func(t *testing.T, content string) {
		path := filepath.Join(t.TempDir(), "unity_0_c.c")
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Skip(err)
		}
		includes, ok := unityIncludes(path)
		// The contract is the point: a file that is not aggregation glue must
		// be refused outright rather than half-parsed.
		if !ok && len(includes) != 0 {
			t.Fatalf("refused the file but returned %d include(s)", len(includes))
		}
		for _, include := range includes {
			if include == "" {
				t.Fatal("an empty include was returned")
			}
		}
	})
}

func FuzzPCHIncludes(f *testing.F) {
	f.Add("/* generated by CMake */\n\n#pragma GCC system_header\n#include \"/src/pch.h\"\n")
	f.Add("#pragma once\n")
	f.Add("#include <")
	f.Add("")

	f.Fuzz(func(t *testing.T, content string) {
		path := filepath.Join(t.TempDir(), "cmake_pch.h")
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Skip(err)
		}
		for _, include := range pchIncludes(path) {
			if include == "" {
				t.Fatal("an empty include was returned")
			}
		}
	})
}
