package generate

import (
	"os"
	"path/filepath"
	"testing"
)

func writeFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestUnityIncludesReadsTheGeneratedIncludeList(t *testing.T) {
	// Exactly what CMake generates, comments included. Section 17.1 permits
	// this parse: it is deterministic and executes nothing.
	path := writeFile(t, t.TempDir(), "unity_0_c.c", `/* generated by CMake */

/* NOLINTNEXTLINE(bugprone-suspicious-include) */
#include "/src/main.c"

/* NOLINTNEXTLINE(bugprone-suspicious-include) */
#include "/src/mod_a.c"
`)
	includes, ok := unityIncludes(path)
	if !ok {
		t.Fatal("a generated unity source was rejected")
	}
	if len(includes) != 2 || includes[0] != "/src/main.c" || includes[1] != "/src/mod_a.c" {
		t.Errorf("includes = %v", includes)
	}
}

func TestAFileWithRealCodeIsNotAggregationGlue(t *testing.T) {
	// The content signal of section 17.1 is "only comments and includes".
	// Anything else means guessing, and guessing is worse than failing.
	path := writeFile(t, t.TempDir(), "unity_0_c.c", "#include \"a.c\"\nint main(void){return 0;}\n")
	if _, ok := unityIncludes(path); ok {
		t.Error("a file containing code was accepted as a unity source")
	}
}

func TestBlockCommentsSpanningLinesAreSkipped(t *testing.T) {
	path := writeFile(t, t.TempDir(), "unity_0_c.c", "/* generated\n   by CMake */\n#include \"a.c\"\n")
	includes, ok := unityIncludes(path)
	if !ok || len(includes) != 1 {
		t.Errorf("includes = %v, ok = %v", includes, ok)
	}
}

func TestPCHIncludesToleratePragmas(t *testing.T) {
	// The generated aggregation header carries a pragma, which is not a
	// refusal signal the way it is for a unity source.
	path := writeFile(t, t.TempDir(), "cmake_pch.h", "/* generated by CMake */\n\n#pragma GCC system_header\n#include \"/src/pch_only.h\"\n")
	includes := pchIncludes(path)
	if len(includes) != 1 || includes[0] != "/src/pch_only.h" {
		t.Errorf("includes = %v", includes)
	}
}

func TestPCHArtifactsAreNeverComponents(t *testing.T) {
	// Section 14.5: the aggregation header, its source and the compiled header
	// are transient build artifacts.
	for _, path := range []string{
		"build:CMakeFiles/app.dir/cmake_pch.h",
		"build:CMakeFiles/app.dir/cmake_pch.h.c",
		"build:CMakeFiles/app.dir/cmake_pch.hxx.cxx",
	} {
		if !isPCHArtifact(path) {
			t.Errorf("isPCHArtifact(%q) = false", path)
		}
	}
	if isPCHArtifact("project:src/cmake_pchopt.h") {
		t.Error("an ordinary header was taken for a PCH artifact")
	}
}

func TestForcedIncludesAreReadFromTheCompileCommand(t *testing.T) {
	// A GCC dependency file never names the aggregation header, so the compile
	// command is the only evidence that the PCH applies to this unit.
	got := forcedIncludes([]string{"cc", "-g", "-include", "/b/cmake_pch.h", "-o", "a.o", "-c", "a.c"})
	if len(got) != 1 || got[0] != "/b/cmake_pch.h" {
		t.Errorf("forcedIncludes() = %v", got)
	}
	if got := forcedIncludes([]string{"cl", "/FIc:\\b\\pch.h"}); len(got) != 1 {
		t.Errorf("MSVC forced include not recognized: %v", got)
	}
	if got := forcedIncludes([]string{"cc", "-I", "/usr/include"}); len(got) != 0 {
		t.Errorf("an include path was taken for a forced include: %v", got)
	}
}

func TestLTOIsDetectedFromCompileFlags(t *testing.T) {
	if !hasLTOFlag([]string{"cc", "-flto=thin", "-c", "a.c"}) {
		t.Error("-flto=thin not detected")
	}
	if hasLTOFlag([]string{"cc", "-fltoxyz"}) {
		t.Error("a flag merely starting like -flto was taken for LTO")
	}
}
